### ISSUE TITLE
remove whitespace from the hero background

### ISSUE THREAD

**Issue by rishipurwar1** [Ninja-Developers/Tech_Phantoms_website#105]
**Describe the bug**
There is too much white space below and above the hero background.

**To Reproduce**
1. Go to the homepage of the website
2. See error

**Expected behavior**
There should be a less padding

**Screenshots**
![Shot 0006](https://user-images.githubusercontent.com/57035408/94435231-7bf20180-01b8-11eb-8d02-5588c288ef76.png)
![Shot 0007](https://user-images.githubusercontent.com/57035408/94435237-7d232e80-01b8-11eb-9b9e-4c67665ebd27.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome

**Comment by rishipurwar1** [comment]
I would like to work on this issue

**Comment by imabp** [comment]
@rishipurwar1 
Thanks for pointing this out. You can work on this issue.
We are using Chakra UI.
You can fix this by changing this line [here](https://github.com/Ninja-Developers/Tech_Phantoms_website/blob/c316215cccc1579d8159874f8ed82bfe9c73625f/src/components/sections/landing_top.js#L24) 
by replacing it with this line below  👇 : 

` mt={{ md: "5%", xs: "5px", sm: "100px", lg: "5%" }}`

**Comment by rishipurwar1** [comment]
Thanks for assigning me this issue...

**Comment by imabp** [comment]
@rishipurwar1 Send PR to development branch.

**Comment by rishipurwar1** [comment]
Ok! I'll do that...

**Comment by imabp** [comment]
Are you working on it @rishipurwar1

**Comment by rishipurwar1** [comment]
I am working on it. Today, I'll make a pr

**Comment by rishipurwar1** [comment]
Please add hackoctober label to this issue.

**Comment by imabp** [comment]
PRs with Hacktoberfest Label will be merged on or after 1st October.

@Souvikns @rishipurwar1

**Comment by imabp** [comment]
Assigned to @rishipurwar1

**Comment by rishipurwar1** [comment]
Is it look good now?
![2020-09-30 15_33_56-Greenshot](https://user-images.githubusercontent.com/57035408/94672191-89cb9200-0332-11eb-92db-f3324cf11e31.png)

**Comment by imabp** [comment]
@rishipurwar1 can you show the mobile view too ?

**Comment by rishipurwar1** [comment]
Mobile View Screenshot
![localhost_3000_(iPhone X)](https://user-images.githubusercontent.com/57035408/94679871-71fa0b00-033e-11eb-9500-5dfe7f9482a6.png)

**Comment by imabp** [comment]
Great Send PR to development branch
@rishipurwar1

**Comment by imabp** [comment]
We will merge it on or after 1st October

**Comment by Coderu2058** [comment]
want to contribute

**Comment by rishipurwar1** [comment]
@Coderu2058 This issue is already solved.
