### ISSUE TITLE
Design 404 page

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#107]
Till now, we don't have a  Error 404 Page yet. 
So this is call for UI designers to prepare a  creative design based on current theme for 404  page

PS: This is hacktoberfest labelled. Will be merged on or after 1st October

**Comment by zygisS22** [comment]
Hi there, can i give it a try?

**Comment by TheCoderNikhil** [comment]
I can do

**Comment by ampsteric** [comment]
I would love to work on this issue. please assign it to me.

**Comment by imabp** [comment]
@TheCoderNikhil @ampsteric  you both can start working on it. Best design will be merged.

Make sure you send PR to `development` branch

**Comment by nitrogenous** [comment]
I would love to work on this issue and create PR asap

**Comment by sandy9808** [comment]
I am also working on it..

**Comment by imabp** [comment]
Go Ahead 
@sandy9808 
@ampsteric 
@TheCoderNikhil 

Assigning you three.
Best design will be considered.

Send PR to `development` branch

**Comment by nitrogenous** [comment]
I also would love to work on this @imabp

**Comment by ampsteric** [comment]
The 404 Error Page has been added.
I have created a new Component(ErrorPage) in the Components folder.
please review and accept the PR.

#107 has been resolved.

its my kind request to @imabp that please accept the PR as soon as possible so that it can be counted for the Hacktoberfest as well.


best regards,
ampsteric

**Comment by Bhuvan804** [comment]
Can i work on it?

**Comment by heet-vakharia** [comment]
Can I Do it?

**Comment by sandy9808** [comment]
Please Do review my PR. https://github.com/Ninja-Developers/Tech_Phantoms_website/pull/142

**Comment by Rihanat** [comment]
I can do this, can I go ahead?

**Comment by OmShrivastava19** [comment]
Hello, i would love to work on this..

**Comment by imabp** [comment]
Issue has been solved
Merged PR #142 to development.
Thankyou @sandy9808 for contributing to Tech Phantoms.

@OmShrivastava19 @Rihanat @Bhuvan804 @ampsteric  please look into other issues, or if you have any feature in your mind, to be implemented for our website. you can create new issues

**Comment by ampsteric** [comment]
atleast Look at the page that I had made.
it was totally dynamic and not only static.

![404page](https://user-images.githubusercontent.com/56419358/94897515-72fd7a80-04ad-11eb-87cf-69991c07666a.PNG)

**Comment by imabp** [comment]
@ampsteric we have reviewed it.
Suggestions:
You have to research a bit more about how react router error 404 works
Design is not matching with the theme.
As mentioned in the Readme, we are using Chakra UI . But you have implemented your own custom CSS which overrides the theme file of Chakra UI. 

There are the reasons why we cannot merge your PR.

**Comment by imabp** [comment]
Moreover, we assigned three of you the issue on the same date and same time.
@sandy9808 @ampsteric @TheCoderNikhil 

But only @sandy9808 came up with fully functional error page, matching the theme, including react router. 
So it was clear that we have merged his PR.
