### ISSUE TITLE
Code the Registration Page  UI 

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#109]
We are planning to launch registration page for our community. Henceforth it would be amazing, to see the code in Action

**We are using Chakra UI**

Steps:
1. Create a branch at your fork, `feat-username-regpage`
2. Comment with Screenshot to this issue
3. Send PR to `development branch`

![image](https://user-images.githubusercontent.com/53480076/94658740-d4dca980-0320-11eb-8a65-bac486e03ff8.png)

**Comment by imabp** [comment]
This issue is in reference to #108

**Comment by greyGroot** [comment]
@imabp hi, i'm interested in solving this issue. Just want to clear something. What should happen, what user clicks on "Join us" button?

**Comment by rarchitgupta** [comment]
I'd like to try this. Just to be clear, I'm supposed to recreate the page as shown above using React and Chakra UI?

**Comment by imabp** [comment]
Yes @rarchitgupta you have to create this using React and Chakra UI 
You can create a directory for this `src/components/forms`

Just need to make the UI and rest functionality we will add it on later

**Comment by rarchitgupta** [comment]
![1601470127477_regpage__01](https://user-images.githubusercontent.com/52240360/94687212-93142900-0349-11eb-8920-40e316a34c5c.png)

This is what I've done so far. On reducing page-width to mobile, this layout can no longer be used and probably has to be changed to a layout where one form is below the other. I would love to fix that if someone could give me a few hints on how to account for page width and render two different layouts conditionally.

**Comment by imabp** [comment]
Nice work @rarchitgupta 
I reviewed the code
There were some mistakes like, fontSize was hardcoded, so I have fixed the hardcode

Now I am performing some alignment test of buttons to check edge cases.

As this is hacktoberfest issue, we will merge it on or after 1st October

**Comment by rarchitgupta** [comment]
@imabp great! Thank you :)

**Comment by imabp** [comment]
@rarchitgupta you can use ChakraUIs flex module  [here](https://chakra-ui.com/flex) to make things mobile responsive. 
Need not worry, we will be implementing it at our end. 

Just for your info we are coming with new issues for more pages, so you can implement there too..

**Comment by rarchitgupta** [comment]
Yes I'll check them out for sure

**Comment by jay-deep** [comment]
Can I work on this?
