### ISSUE TITLE
Airtable Error

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#113]
**Airtable Error Cannot fetch data**
Not able to fetch Team and Event data from airtable.

**To Reproduce**
1. Go to 'https://devtechphantoms.netlify.app/events.'
2. See error

**Expected behavior**
Events and Team Members should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/53480076/94701067-d70f2a00-0359-11eb-8e8e-67388f7dbd26.png)

**Comment by Souvikns** [comment]
# I checked, and it was working 
![Screenshot 2020-09-30 at 8 38 33 PM](https://user-images.githubusercontent.com/41781438/94703915-fa87a400-035c-11eb-9433-6f7f058d972e.png)

**Comment by Souvikns** [comment]
@imabp check once, if it is a problem of the internet.

**Comment by imabp** [comment]
@Souvikns check here where development branch is hosted in this url

https://devtechphantoms.netlify.app

**Comment by Souvikns** [comment]
Have you set the env variables correctly

**Comment by Souvikns** [comment]
Also check if someone has changed anything, as the master branch is working on previous commits, then the issue must have arrived in newer commits.

**Comment by Souvikns** [comment]
So I was checking the codebase of the development branch and found this 
https://github.com/Ninja-Developers/Tech_Phantoms_website/blob/d11bd0f0c0b1f1c6c13ceaaa0dddc0c9b4cb11f8/src/data/airtable/event.js#L3

**Comment by imabp** [comment]
It should not create any problem as it there running on master and master is working fine.

https://github.com/Ninja-Developers/Tech_Phantoms_website/blob/b23cb4d7c9a9d9b5691dd2b07f96cc546a264e93/src/data/airtable/event.js#L3

**Comment by Souvikns** [comment]
check the env then.

**Comment by imabp** [comment]
@rarchitgupta  please do not upgrade any package versions. 

Development now working successfully.

**Comment by imabp** [comment]
It is fixed now. Closing the issue
