### ISSUE TITLE
We need documentation for Project Structure

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#114]
Project Directory will help beginners to understand the code.
Project Structure must be saved in root location with name `projectStructure.md`
This structure must describe each and every folders or file and their role in the project.

**Comment by imabp** [comment]
It is now assigned to @ktavleen , but if anyone also interested can also contribute and send the `PR` to `master` branch for this.

**Comment by TomerPacific** [comment]
@imabp , I'd like to help. Is there an example of what the file should look like?

**Comment by imabp** [comment]
@TomerPacific happy to see that.

@ktavleen @TomerPacific you both can divide the work as project structure is vast. Assigning this to you both. 

This is bit lengthy task and also requires proper project folders understanding.  All the best both of you.  @TomerPacific @ktavleen 



For example, this is current structure
![image](https://user-images.githubusercontent.com/53480076/94736624-28cfa880-038a-11eb-8655-516ccaf9f74a.png)

So if I want to document the structure, it should be like.

# `src`
src contains the main source code for the react-app

## `src/assets/`
Assets contain all the community brand assets in `.svg` format

## `src/components/`
Components used in this website
### `src/components/footer`
Contains footer component 
## `src/data/`
Code implementation for communication with Airtable servers.
 ### `src/data/hooks`
All web hooks used in the website are listed here.

**Comment by TomerPacific** [comment]
@imabp , I have opened a PR not because I am finished with the task, but to show you what I am intending to do with it and to ask if this is what you were expecting for it. Please give me feedback if this is what you were looking for (or not).

**Comment by imabp** [comment]
Fine @TomerPacific We have merged it to development branch. You can start working on it. As this would help other assignee to get started.

**Comment by imabp** [comment]
@TomerPacific I have changed the directory of the projectStructure to root . Do update your fork.

**Comment by TomerPacific** [comment]
@imabp , I did not want you to merge my PR, but to give me feedback so I could understand if what I did was what you wanted. I'll continue my work on another feature branch.

**Comment by TomerPacific** [comment]
@imabp , I have created another PR, but in draft status, so you can comment on the progress so far and if any changes are necessary.

**Comment by imabp** [comment]
Great you are going right. 
Loved the documentation
