### ISSUE TITLE
Overflow in projects section in smaller devices 

### ISSUE THREAD

**Issue by Harshchourasiya** [Ninja-Developers/Tech_Phantoms_website#115]
**Describe the bug**
In the project section in smaller device you can see the overflow of project out from the screen

**To Reproduce**
1. Go to project section
2. Go to inspect
3. Click on smaller Device toolbar 
4. You can see the bug

**Expected behavior**
Project section without overflow

**Screenshots**

![IssusSecond](https://user-images.githubusercontent.com/48551992/94716266-383ff900-036c-11eb-9eb4-236186c2cdcf.PNG)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Would you like to work on this issue**
Yes , I Love to.

**Comment by imabp** [comment]
Thankyou for pointing this one out @Harshchourasiya .
Go Ahead. Assigned to @Harshchourasiya 

@Harshchourasiya Make sure you send PR to `development` branch

@Souvikns review this.
