### ISSUE TITLE
design mockup for Team member card

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#12]

**Comment by imabp** [comment]
For Team page designed I liked this one here
https://githubsatellite.com/speakers/

**Comment by puranjay123** [comment]
@imabp  it looks great

**Comment by pixan198** [comment]
Which one would be better for our website's team section?
@imabp  @Souvikns @puranjay123 @JoshuaPoddoku 
Mockup 1
![TEAM 1](https://user-images.githubusercontent.com/56932286/92288038-2ca61180-ef29-11ea-8d9c-c75fff06ea67.png)
---
Mockup 2
![TEAM 2](https://user-images.githubusercontent.com/56932286/92288041-2f086b80-ef29-11ea-93b5-db33602dbfb3.png)

**Comment by puranjay123** [comment]
1st one looks good with all members at one place with no divisons.

**Comment by Souvikns** [comment]
I also designed something like this 
![Team Page](https://user-images.githubusercontent.com/41781438/92291726-91686880-ef37-11ea-844f-0372d12b82be.png)

**Comment by pixan198** [comment]
@Souvikns if nobody is working, can I start working on it?

**Comment by imabp** [comment]
@pixan198 I found @Souvikns design clean and beautiful. Design the card component for Team Member as above using Chakra UI .

**Comment by pixan198** [comment]
@imabp Okay

**Comment by Souvikns** [comment]
@pixan198 tell me if you need the code assets.

**Comment by pixan198** [comment]
Yeah @Souvikns , can you please upload it in the assets folder

**Comment by Souvikns** [comment]
@pixan198 I have added the assets in the repo itself, under src/assets/team
