### ISSUE TITLE
UI improvements (CSS) for Home page

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [Ninja-Developers/Tech_Phantoms_website#124]
**Is your feature request related to a problem? Please describe.**

It does feel uncomfortable when items are not aligned properly, when they don't follow a pattern and have too many alignment lines. This causes trouble for the viewer as it requires to constantly reset the point of focus.

**Describe the solution you'd like or working on**

#### I have made changes
1. To the Hamburger icon padding to match closely to that of the footer.
2. To the alignment of second section of landing_top, made them align horizontally straight to the icon_img.
3. Changed size improvements to illustrations for x-small, small and medium screens.
4. Changed footer social media icons spacing for small screens (actual one was making the footer larger than necessary).

I would like to be assigned for this issue and make a PR.

Thank you 😁

**Comment by Bhuvan804** [comment]
I can add a custom scroll bar. 
Changes will apply to all the pages.

**Comment by imabp** [comment]
@Bhuvan804 refer issue #72

**Comment by imabp** [comment]
Thankyou @AbhinavReddy-Dev  for this amazing contribution
