### ISSUE TITLE
Typos in Development Website page

### ISSUE THREAD

**Issue by Devansu-Yadav** [Ninja-Developers/Tech_Phantoms_website#126]
**Describe the bug**
I noticed a few typos in the Development website's Landing Page
**To Reproduce**
1. Go to ['Development website'](https://devtechphantoms.netlify.app/)
2. Scroll down to 'Vision Section'
3. See typo on line 6, word 6
4. Scroll down to 'Bottom of Landing Page'
5. See typo on line 10, word 4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS, Windows, Linux[e.g. iOS]
 - Browser: All Browsers[e.g. chrome, safari]

**Smartphone (please complete the following information):**
 - Device: All devices[e.g. iPhone6]
 - OS: Android, IOS[e.g. iOS8.1]
 - Browser: All Browsers[e.g. stock browser, safari]

**Additional context**

**Comment by Devansu-Yadav** [comment]
@imabp I have solved this issue can I make a PR?

**Comment by imabp** [comment]
This has already been fixed  now by previous issue .
