### ISSUE TITLE
Responsiveness Issue

### ISSUE THREAD

**Issue by lancaster215** [Ninja-Developers/Tech_Phantoms_website#127]
**Describe the bug**
@768px width (iPad view), the page is cut on /projects page

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="278" alt="Untitled" src="https://user-images.githubusercontent.com/29894579/94778792-75ea6380-03f8-11eb-93d4-77ec7cfe9d23.png">

**Desktop (please complete the following information):**
 - Browser [e.g. **chrome**, safari]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Devansu-Yadav** [comment]
@imabp Can I work on this?

**Comment by Harshchourasiya** [comment]
Hey, I Already work on this issue and make a pull request #155

**Comment by imabp** [comment]
Responsive issue is solved. 

But @lancaster215 @Devansu-Yadav we have this issue coming up related to this : #131 
You can check that out
