### ISSUE TITLE
Create Template For events

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#13]
Every event in the event page will have have some common components like,
- title
- date
- venue
- duration 
- about 
- image

> It will be better to create a component that takes these parameters and render a card, this way we can save development time in the future.

**Comment by imabp** [comment]
@Souvikns  I am making an event  component in `component/event.js` with props as

1. title
2. date
3. venue
4. duration
5. about
6. image

So that you can call this with props while using airtable. Is it fine?
@Souvikns Shall I go with this approach

**Comment by Souvikns** [comment]
will these be the values that you will be required, then I will create a airtable table and a react hook to fetch these data

**Comment by imabp** [comment]
These values is in reference to the first comment you mentioned.

**Comment by Souvikns** [comment]
do you need anything else or this these fields are fine

**Comment by imabp** [comment]
@Souvikns 
In order to make events unique, final proposed 
**Serial Number**
Date

**Comment by Souvikns** [comment]
About visualizing all the data for the event organizers would be done in airtable itself.
