### ISSUE TITLE
Project section look more cool when box come in more center

### ISSUE THREAD

**Issue by Harshchourasiya** [Ninja-Developers/Tech_Phantoms_website#132]
**Is your feature request related to a problem? Please describe.**
This is not a bug or a problem but I think Project section look more cool when box come in more center

**Describe the solution you'd like**
make Project section box in center

**Is this a good idea**
comment this idea is good or not

**This is now look like this**

![idea](https://user-images.githubusercontent.com/48551992/94786351-77af2980-03ee-11eb-8237-a41aefbe4d9e.PNG)

**Would you like to work on this idea**
Yes, I love to work but if this is good idea

**Comment by imabp** [comment]
I have raised the issue #131 regarding this. 
Closing this issue
