### ISSUE TITLE
Hacktoberfest Route 

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#14]

**Comment by Souvikns** [comment]
I think rather than building a separate route for hacktoberfest we should dd it in the events page, as it will be shirt lived and we will eventually have to remove it after the event is over.

**Comment by Souvikns** [comment]
@imabp what do you say about this then I will make a data layer for events and also make a feature where only the recent event will be returned, for the main page.

**Comment by imabp** [comment]
Yeas @Souvikns , we must close this hacktober fest route issue. As it is not needed, we will be hosting it from our events page only.
