### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#15]
- [ ] mockup  (@mauriceyeng and @puranjay123  )
- [ ] content (@prachi-ag )
- [ ] code (@Souvikns  )

**Comment by Souvikns** [comment]
- [ ] mockup
- [ ] content

**Comment by imabp** [comment]
![image](https://user-images.githubusercontent.com/53480076/91690775-26f4a880-eb84-11ea-8f53-ed4411202e74.png)

**Comment by Souvikns** [comment]
![Landing Page – 1](https://user-images.githubusercontent.com/41781438/91727278-14e42b80-ebbf-11ea-945c-c731fd9c48dd.png)

**Comment by Souvikns** [comment]
If there aren't any other ideas or variations for design then I suppose we should go with this @imabp

**Comment by JoshuaPoddoku** [comment]
We can try looking on illustrations now as the color and font are almost fixed

**Comment by Souvikns** [comment]
I guess the landing section is looking good, we just need to figure our rest of the design

**Comment by puranjay123** [comment]
![TechPhantoms websitepage](https://user-images.githubusercontent.com/55429956/91893025-31f92700-ecb1-11ea-814a-909433e1f6b7.png)

**Comment by puranjay123** [comment]
@JoshuaPoddoku @vinitshahdeo @imabp @Souvikns  review???

**Comment by puranjay123** [comment]
the main photo is not final

**Comment by Souvikns** [comment]
Converting this theme into mobile will be tough and also building this code to. Try to use the above design but change the ilustration and experiment withthe color. 
> by tomorrow lets get the design down and start coding

**Comment by JoshuaPoddoku** [comment]
Agreed with @souvik

**Comment by Souvikns** [comment]
@puranjay123 also something I would like to add. The design that you sent, has a login and signup button. As we building a portfolio site for our organization, I don't think we will ever have an authentication system. keep this in mid and search some of the portfolio sites for some idea. 

> Good Work Keep It Up 👍

**Comment by puranjay123** [comment]
ok we will add some other buttons here like homepage or search bar . i will edit this

**Comment by Souvikns** [comment]
We will not create a navbar but rather use menu icon as it looks clean.

**Comment by Souvikns** [comment]
The mockup that I sent, the first part will be the same design something for the rest of the page. 
> @imabp pls comment down all the sections that our homepage will have.

**Comment by Souvikns** [comment]
@JoshuaPoddoku you can start work on the landing section,  guess we already have the assets in the repo, you can use that. 
> I am working on the navbar

**Comment by puranjay123** [comment]
> 
> 
> We will not create a navbar but rather use menu icon as it looks clean
![a111](https://user-images.githubusercontent.com/55429956/91901160-77bbec80-ecbd-11ea-8d3b-2b3ca4f3de1c.jpeg)
i think we can add small icons like this from which we have not to create navigation bar and it looks clean also.

**Comment by Souvikns** [comment]
We will have a dropdown menu where we can have these icons.

**Comment by Souvikns** [comment]
## So the pages that we will have 
- index page 
- events page 
- team page 
- join our community page (probably)

> make icons accordingly

**Comment by puranjay123** [comment]
@Souvikns  i think the BLOGS page should also be added or like there should be a page like resourrces which include  documentation and blogs of our community

**Comment by Souvikns** [comment]
Call out for landing page content, and the rest of the landing page design.

**Comment by imabp** [comment]
@Souvikns @JoshuaPoddoku @garimasingh128 @AnubhavMadhav @pixan198 

Landing Page has been completed with sample content and also optimized for mobile view.

Content Writers @prachi-ag @SavageShift  please help us with content

**Comment by souvik** [comment]
Hi,
From few days I am getting these emails. But I really don’t know how I became a part of this group. I think you guys are mistakenly added me in this group.


Sent from Yahoo Mail for iPhone


On Tuesday, September 8, 2020, 10:49 PM, Abir <notifications@github.com> wrote:




Closed #15.

**Comment by imabp** [comment]
@souvik  we are sorry, but I think there was mistakenly put up your github username tag, as we have a person named souvik. thats why. Apologies. 🙌
