### ISSUE TITLE
Events route is breaking

### ISSUE THREAD

**Issue by PrathamDogra** [Ninja-Developers/Tech_Phantoms_website#160]
**To Reproduce**
1. Go to the top right hamburger and then click on the Events
2. On clicking it is giving the following error

**Expected behavior**
It should open the Events page.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/43649218/94959974-b8eb2a80-050f-11eb-96c2-c80090588808.png)

**Comment by PrathamDogra** [comment]
I would like to go through this issue.

**Comment by imabp** [comment]
@PrathamDogra 
We have rechecked the deploys 
Everything is fine. 
Can you check the changes if you have made any using `git status`

**Comment by imabp** [comment]
@PrathamDogra if you are new contributor please go through Readme once, we have instructions to setup Airtable servers locally using dummy api keys

**Comment by PrathamDogra** [comment]
> @PrathamDogra
> We have rechecked the deploys
> Everything is fine.
> Can you check the changes if you have made any using `git status`

I am running the project in the local server and I haven't made any changes.

**Comment by imabp** [comment]
@PrathamDogra 
Please check you have installed dummy Api keys in dotenv file.

We have documented it in our readme [here](https://github.com/Ninja-Developers/Tech_Phantoms_website#-api-key-installation-dummy)


> > @PrathamDogra
> > We have rechecked the deploys
> > Everything is fine.
> > Can you check the changes if you have made any using `git status`
> 
> I am running the project in the local server and I haven't made any changes.

**Comment by PrathamDogra** [comment]
Yes, @imabp I have added the API keys in the .env file. Here is the issue which I am facing in the local
![tech](https://user-images.githubusercontent.com/43649218/94962971-0027ea00-0515-11eb-9cf3-d931b2a0ddf3.gif)

**Comment by PrathamDogra** [comment]
It is happening due to the date field in the uniqueDates (inside events.jsx ) file. Sometimes the date field is not there inside the fields object hence this error is occurring. This could be resolved if we use some check before rendering the dates of events that if the event date field is there show the date else not.

**Comment by imabp** [comment]
@PrathamDogra 

Actually the problem is with the response the Airtable is sending, because we need to update few fields because of few  critical commits were based on airtable which have only accounted to non-exposed apis., but not for dummy apis.

I will resolve the airtable server issue by tomorrow.

**Comment by imabp** [comment]
Closing this for now, because it is something, not open sourced. 
We are not exposing the actual APIs
And based on the current scenario... 

Issues referring Event Page are on hold now, till we update the dummy apis

**Comment by imabp** [comment]
@PrathamDogra now things are working
I have updated the Dummy API keys [here](https://github.com/Ninja-Developers/Tech_Phantoms_website#-api-key-installation-dummy)
