### ISSUE TITLE
Add redirect file 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#23]
As we are hosting our website on netlify we need to add a redirect file, otherwise our deployed application will have issues when refreshing pages and also to go to custom routes. 

> can refer to this [issue](https://github.com/anushbhatia/Social-Scheduler/issues/38) for better understanding

**Comment by imabp** [comment]
Issue Solved hosted at : https://techphantoms.netlify.app/
