### ISSUE TITLE
Follow and custom tweet option using twitter API

### ISSUE THREAD

**Issue by JoshuaPoddoku** [Ninja-Developers/Tech_Phantoms_website#28]
Example
Check the bottom of the page: https://anubhav-madhav-blogs.herokuapp.com/introduction-to-programming-languages

**Comment by imabp** [comment]
Code for Integration of twitter follow button.
`<a href="https://twitter.com/tech_phantoms?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @tech_phantoms</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`
