### ISSUE TITLE
Create Landing section

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#30]
Check the design from the connected epic.
> All the required code is assets are in the repo itself

**Comment by hkaur008** [comment]
i can contribute to frontend designing .

**Comment by Souvikns** [comment]
@hkaur008 happy to see you interested in contributing. we are still coming up with the design though the landing section is pretty much fixed for the design check #15 the design that I have commented. You can find the assets inside repo itself. As we are using [react](https://reactjs.org/) and [chakra ui](https://chakra-ui.com/) to develop this web page. I would suggest you do the same. You use use css also to design the component. 
keep these in mind while coding 
- Create a separate component under components library 
- Use functional components instead of class components 
- Use proper directory structure

> If you are new to react you can ask for help in our [slack channel](https://tech-phantoms.slack.com/archives/C01A1K1S6H0)

**Comment by imabp** [comment]
If any doubts feel free to ask @imabp  @Souvikns  @ joshua

**Comment by imabp** [comment]
@hkaur008 Can you let us know the progress.
