### ISSUE TITLE
BUG: Routing in production results in 404

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#32]
## Reproduce Bug.

1. Go to: https://condescending-swartz-83b809.netlify.app/
2. Click on hamburger menu 
3. Click on any following route.
4. 404 Page 

![Bug](https://user-images.githubusercontent.com/53480076/92039835-62b18d00-ed93-11ea-8025-101bdb167740.gif)

**Comment by Souvikns** [comment]
For this only I created the issue #23. By adding a `_redirect` file it can be fixed
