### ISSUE TITLE
Change Favicon, Meta Data of Index.html

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#35]
### Task 1 
Find the favicon at: `src/assets/logo.svg` 
Find `index.html` here at `public/index.html`

### Task 2
Update meta data from
`<meta
      name="description"
      content="Web site created using create-react-app"
    />`
to
`<meta
      name="Tech Phantoms"
      content="An Open Tech Community "
    />`

**Comment by hnishal** [comment]
I would like o work on it

**Comment by imabp** [comment]
@hnishal Great go ahead !

**Comment by imabp** [comment]
@hnishal let me know, if you are facing any issue

**Comment by hnishal** [comment]
@imabp i made changes in the meta tag in index.html, is that all that was to be done?

**Comment by imabp** [comment]
@hnishal 

1. Update your fork with the original Repository. [Refer Here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)
2. Create Pull request.
3. I will merge the changes

**Comment by hnishal** [comment]
@imabp how do i change the favicon

**Comment by imabp** [comment]
@hnishal 
Navigate to `public/index.html`
Add the following code
`<link rel="icon" type="image/svg" href="../src/assets/logo.svg">`

**Comment by Souvikns** [comment]
@imabp has this issue bin fixed.

**Comment by imabp** [comment]
Great @hnishal Merged !
