### ISSUE TITLE
Create holder compnent for events 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#37]
As the data layer part is complete, all we have to do is create a holder component that will receive data as props and render a single event card.

**Comment by imabp** [comment]
@Souvikns @JoshuaPoddoku  Please review
Here is proposal for an event card props I am preparing
1. **Event Serial Number** (required)
3. **Event Image Link** (required, default image: https://drive.google.com/file/d/13UqDB73ie5a-2LhF4RpepZdWa4QhPWTz/view)
2. **Event Title** (required)
3. **Event Description** (required)
4. **Event Date** (required)
5. **Event Register Link** (required, can use  a default table airtable for this see below 👇)
6. **Event  Recording Link** (Optional, for past events, can be updated later)
5. **Event Time (Time Zone) ** (required)
6. **Duration**(required)
7. **MLSA Event**(Options (yes or no))

**Comment by imabp** [comment]
Event holder Created @Souvikns
