### ISSUE TITLE
Links in react drawer is reloading the page

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#42]
Currently, the links in the drawer are not using react-router-dom links and thus it is reloading the pages, I guess this issue could be solved by just adding **react-router-dom** links component.

**Comment by imabp** [comment]
Are we going to use history too ?

**Comment by Souvikns** [comment]
First, try importing Link from `react-router-dom`, It should fix this, but if it does not then use history and create button.

**Comment by imabp** [comment]
Successfully Implemented `react-router-dom` 
Build Success
