### ISSUE TITLE
Fixing footer and its icons

### ISSUE THREAD

**Issue by JoshuaPoddoku** [Ninja-Developers/Tech_Phantoms_website#48]
I guess uniform icons would be better either material UI or just filled ones with color. We can try and see.

**Comment by imabp** [comment]
@JoshuaPoddoku go ahead!

**Comment by imabp** [comment]
@JoshuaPoddoku What is the update for it
?

**Comment by adnansalik** [comment]
Hey, can I work on this issue?

**Comment by imabp** [comment]
Go Ahead @adnansalik . 
We will be keeping this assigned to you for next  three days.

**Comment by JoshuaPoddoku** [comment]
Suggested for icons: https://remixicon.com

**Comment by adnansalik** [comment]
So whenever I try typing npm start I get an errors in localhost asking for an API key to connect to Airtable. I'm really new to this so I am a bit confused, so can anyone help me out?
I did npm install before running and npm is globally installed
I have a picture below attached
![Screenshot from 2020-09-26 18-58-17](https://user-images.githubusercontent.com/46531078/94341844-664ed180-002a-11eb-95b5-639c836716c0.png)

**Comment by imabp** [comment]
@adnansalik 
Apologies for that. We have now fixed it, Please read this fix [here](https://github.com/Ninja-Developers/Tech_Phantoms_website/blob/master/README.md#api-key-installation)

**Comment by adnansalik** [comment]
Is this fine or should I add something else?
![Screenshot from 2020-09-26 23-38-27](https://user-images.githubusercontent.com/46531078/94347412-8e056000-0051-11eb-906b-aba000937003.png)

**Comment by imabp** [comment]
@adnansalik can you show the Mobile View

**Comment by adnansalik** [comment]
Here you go
![Screenshot from 2020-09-26 23-52-13-cropped](https://user-images.githubusercontent.com/46531078/94347624-70d19100-0053-11eb-85c6-9d9cdeacff2a.jpg)

**Comment by imabp** [comment]
For Mobile view, can you put those icons in vertical alignment

**Comment by imabp** [comment]
Make sure u send the PR to development branch .

**Comment by adnansalik** [comment]
Yeahh okay

**Comment by adnansalik** [comment]
In mobile view I successfully aligned the icons vertically by changing the values of columns to 1 in SimpleGrid but I don't know where to add this rule as I in CSS media query I don't think it's possible change values of an element.
![Screenshot from 2020-09-27 12-17-01](https://user-images.githubusercontent.com/46531078/94358072-e7a27480-00bb-11eb-8a88-2aebf9d646a6.png)

**Comment by imabp** [comment]
@adnansalik you can take help of the line number 21 [here](https://github.com/Ninja-Developers/Tech_Phantoms_website/blob/9fa0b68d2a765c9168a94b0a6b5dc036573149d5/src/components/sections/landing_top.js#L21) for your reference

**Comment by imabp** [comment]
After you send PR gets merged to development branch, you can see it here: (This is instant view of development after merging) 
https://devtechphantoms.netlify.app/

And when core members clean the code and merge it to master, you can see it here (This is periodic) : 
https://techphantoms.netlify.app
