### ISSUE TITLE
Connect event holder component to data layer 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#49]

**Comment by Souvikns** [comment]
@imabp I need some details 

>  eventNo: Event Serial Number (required)
  eventImg: Event Image Link (required, default image: https://drive.google.com/file/d/13UqDB73ie5a-2LhF4RpepZdWa4QhPWTz/view)
  eventTitle: Event Title (required)
  eventDesc: Event Description (required)
  eventDate: Event Date (required)
  eventReg: Event Register Link (required, can use a default table airtable for this see below 👇)
  eventRec: Event Recording Link (Optional, for past events, can be updated later)
  eventTime: **Event Time (Time Zone) ** (required)
  eventDuration: Duration(required)
  mlsaEvent: MLSA Event(Options (yes or no))          
  eventRSVP            

I guess these are all the props that you are using. 

The props I am storing in my table, and I guess you need to change your props to these
> title
description 
eventImg
date
reg_link
mlsa_event
duration
rsvp
event_recording_link

**Comment by imabp** [comment]
@Souvikns done

**Comment by imabp** [comment]
@Souvikns 
Follow this code for extracting date and time separately from ISO.

## Approach 1 (Manual)

**Step 1:**
Convert ISO Date to string (if data received already in  string skip to step 2)
```js
/*date received from the airtable stored in variable date */

/*date converted to String*/
str_date = date.toISOString()    // For Example: str_date="2020-09-10T13:30:00.000Z"

```
**Step 2:**
Split the `str_date` with separator as T. 

```js
const time_details=str_date.split('T')
const date=time_details[0]; //date=2020-09-10
const time=time_details[1]; //time=13:30:00.000Z
```

## Approach 2 (MomentJS)

Refer [here](https://momentjs.com/)

**Comment by Souvikns** [comment]
I am receiving the time and date in string format, and the holder is also taking date and time in string format, then I think date & time conversion logic should also be in Holder component itself.

**Comment by imabp** [comment]
@Souvikns Logic built in event holder and successfully tested on client

**Comment by Souvikns** [comment]
Then I guess just passing in the appropriate props will fix it

**Comment by Souvikns** [comment]
I changed the folder structure that's why it is conflicting. 
The code you had written in `index.js`. I shifted that code inside `holder.jsx` and created `events.jsx` for creating lists of events. 

and in `index.js` i just created appropriate exports
```jsx
import Holder from './holder'
import Events from './events'

export { Holder, Events }
```

**Comment by imabp** [comment]
Proper Props:
![image](https://user-images.githubusercontent.com/53480076/92598135-07692880-f2c6-11ea-9864-80549a132dc0.png)




Example Holder
![image](https://user-images.githubusercontent.com/53480076/92598070-e99bc380-f2c5-11ea-99ee-4fd20787dfa9.png)
