### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#5]

**Comment by Souvikns** [comment]
> Rough sketch
![Events Page](https://user-images.githubusercontent.com/41781438/91648856-58894900-ea8a-11ea-9a3a-8aa3b0af3556.png)

**Comment by hkaur008** [comment]
i can contribute to this

**Comment by Souvikns** [comment]
@hkaur008 this is only for discussion, #37 was the issue for creating holder components, I think @imabp is doing that. we will open new issues soon, also you can create an issue if you found any bug.

**Comment by imabp** [comment]
@hkaur008 I have completed the component for event holder with props, mentioned in 
[`src/components/EventHolder/index.jsx`](https://github.com/Ninja-Developers/Tech_Phantoms_website/blob/master/src/components/EventHolder/index.jsx)

**Comment by imabp** [comment]
@hkaur008 you can still look on other issues .
