### ISSUE TITLE
Missmatch with production and master branch

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#53]
## Problem 
Currently, the code in the master branch is working just fine without any errors. Still in the [dev branch](techphantoms.netlify.app/), the code is I guess commits behind. 

## Expected behavior 
![Screenshot 2020-09-10 at 5.23.14 PM.png](https://images.zenhubusercontent.com/5e5c04ddd0668b3a2093f19f/12631045-2e0e-440e-8d3e-af79cba95f5c)

If we take a look in the `src/pages/event` component, we find 

```

import React from 'react'
import { Events as Evnts, Holder } from '../components/EventHolder'
import {
    Box,
} from '@chakra-ui/core'


const Events = props => {

    return <>
        <center>
            <span style={{ fontSize: 50 }}>Events</span><br />
        </center>
        {/* Sample Event Holder */}

        {/* <EventHolder
         description="Git and GitHub 101"
         date="2013-03-10T02:00:00Z"
         title="HacktoberFest with Tech Phantoms"
         mlsa_event={true} 
         event_recording_link="some link"
         />*/}

        <Box style={{ margin: '12px 10px' }}>
            <Evnts />
        </Box>
    </>
}

export default Events
```
As the previous, the `<EventHolder />` is commented out and thus it should not render it. but render `<Evnts />`. this is what is happening in the local server. 

## Current behavior 
![Screenshot 2020-09-10 at 5.23.53 PM.png](https://images.zenhubusercontent.com/5e5c04ddd0668b3a2093f19f/57229a9d-1637-4bce-aa1b-27fa8f3459bb)

**But the in the production still the previous code that has been commented out is being rendered.**

## Speculation 
What I believe is there might be a mismatch of the branch for deployment as new changes made to the master branch are not being deployed.

**Comment by imabp** [comment]
I am working on this issue.
It is related to build fail issues. Will push the changes within few minutes

**Comment by Souvikns** [comment]
Well now that is fixed, our codebase has no errors or warnings. Let's aim in keeping it that way. @imabp from now we should merge pr if and only if all the checks have passed.
