### ISSUE TITLE
Connect Teams page with data layer

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#57]
As the team member holder component is built. Now I guess we should start connecting it with **airtable**.

**Comment by Souvikns** [comment]
![Screenshot 2020-09-13 at 2 13 42 AM](https://user-images.githubusercontent.com/41781438/93004691-ef640400-f566-11ea-84de-5c4d329e78ad.png)

## Problem 
As we can see from the above screenshot, not every member Github profile. 

## Solution 
This problem can be solved in two ways 
- add Github account for the members that are missing. 
- instead of GitHub, we can display either medium or Instagram profile.

**Comment by imabp** [comment]
Also added conditional filter for those having github or not, it will show  that links only, which is there live.
