### ISSUE TITLE
Change in the design of the events component.

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#68]
# Current View
![image.png](https://images.zenhubusercontent.com/5e5c04ddd0668b3a2093f19f/c03a6863-b7f6-49ca-91b0-c7b3e99e188d)

---

## Changes
- [x] Firstly we should go with a better formating for time and date 
- [x] We will be removing the **RSVP** functionality because most events will have a event link so I think we should just keep a event link instead. 
- [x] Title of the event should have a bigger *font* and also be **bold**, as it should be the center of attention. 
- [x] I think we can experiment with the shadow a little bit
- [ ] Design the Event page, with the new layout

> @imabp comment when you are free for this.

**Comment by Souvikns** [comment]
## I thing we should create a card that is like kinda small and has even sides
![image](https://user-images.githubusercontent.com/41781438/94018967-d82adf00-fdce-11ea-84aa-ed1ebd72db63.png)

**Comment by Souvikns** [comment]
Working on formatting date and time

**Comment by Souvikns** [comment]
Most of the work is done, I have also created the proposed format of the **event page**. Now we just have to design a bit and it will be done.

**Comment by imabp** [comment]
@Souvikns I am removing the assignees as new comers might be interested.

**Comment by Souvikns** [comment]
No, I am working on this issue. There are other projects as well try to create issues there.

**Comment by Souvikns** [comment]
# Check the new design.

![image](https://user-images.githubusercontent.com/41781438/94252528-ad14cc80-ff41-11ea-9041-b143557d7859.png)

**Comment by imabp** [comment]
Great Merging

**Comment by Souvikns** [comment]
If this is fixed I think we should close this.
