### ISSUE TITLE
Design Logo

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#7]
Create an abstract logo that speaks **Tech_Phantoms**

**Comment by Souvikns** [comment]
![ghost (2)](https://user-images.githubusercontent.com/41781438/91648303-861ec400-ea83-11ea-909b-63a19f0b5544.png)

**Comment by imabp** [comment]
Check here: https://github.com/Ninja-Developers/Tech_Phantoms_website/tree/master/src/assets
Updated
