### ISSUE TITLE
Alignment of Brandname in Dark Mode 

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#70]
![Scroll](https://user-images.githubusercontent.com/53480076/94234376-2fdc5e00-ff27-11ea-80c4-ee5388a8ab89.gif)

**Comment by imabp** [comment]
I think this is the problem with dark mode svg spacing
https://github.com/ninja-developers/Tech_Phantoms_website/blob/master/src/assets/DarkMode_techphantoms.svg

**Comment by Tomekmularczyk** [comment]
@imabp can I take it?

**Comment by imabp** [comment]
It was minor issue @Tomekmularczyk , and has been resolved now. You can take a look on other issues like #39
