### ISSUE TITLE
Custom Scroll bar for the website

### ISSUE THREAD

**Issue by imabp** [Ninja-Developers/Tech_Phantoms_website#72]
## Requirement:
To have a custom scrollbar design which suits the background and plus makes website look more aesthetic

![image](https://user-images.githubusercontent.com/53480076/94236152-5e0f6d00-ff2a-11ea-84cd-52b4bcc576b2.png)

**Comment by sejalshri** [comment]
@imabp , i would like to work on this issue as a part of Hacktoberfest. Please assign it to me.

**Comment by KushalBhanot** [comment]
Hey! I would like to work on this issue.

**Comment by nidhishs** [comment]
@imabp Hey, I have worked quite a bit on designing websites and also have some skills with graphic designing. I'm also in the process of designing my [website](https://nidhishs.github.io). This should give a vague idea about my designing skills.

**Comment by devblin** [comment]
Hey, I would like to work on this issue.

**Comment by imabp** [comment]
That's Overwhelming. ✌ 
@KushalBhanot @devblin @nidhishs  @sejalshri 

We respect all of your contributions. But can have only one get merged. I also recommend you to see the issue #48 , if you are good with CSS as it is also a part of hacktoberfest. 
 
*Based on Guidelines of Hacktoberfest*

1. **Go Ahead with your individual designs for scroll bar in your fork  and send us a PR.** 👩‍💻 
2. After sending PR, you can attach the screenshot in this issue itself.
3. Core members of our organization will review and merge the best one.

**Comment by imabp** [comment]
We are assigning this to all of you. And the best design will be selected.

**Comment by imabp** [comment]
@JoshuaPoddoku review this Issue

**Comment by imabp** [comment]
How is it going. Do give a star to repo. If you are liking it ! ✌✌

**Comment by imabp** [comment]
@devblin @KushalBhanot @nidhishs @sejalshri  are  you working on it ? What is the status

**Comment by nidhishs** [comment]
I haven't started yet. Will try to start today.

**Comment by imabp** [comment]
Just  a info, make sure, you send PR to development branch.

**Comment by JoshuaPoddoku** [comment]
Try to use minimalistic  and use same theme colors for the scroll bar.
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by nidhishs** [comment]
> Try to use minimalistic and use same theme colors for the scroll bar. https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
> […](#)

I'm sure you know, but just so that we are on the same page, that solution doesn't work on Firefox. I was considering adding a <div> and using on scroll events to make a custom scrollbar. Not exactly sure how good that'll work. But if you are fine with incompatibility on Firefox, ::-webkit-scrollbar should be relatively quick to implement.

**Comment by JoshuaPoddoku** [comment]
Yes, most of the devs prefer firefox developer edition. So let's go with
scroll event.

**Comment by imabp** [comment]
Go Ahead with div tag and using scroll events for custom scrollbar

**Comment by nidhishs** [comment]
> @nidhishs Go Ahead with div tag and using scroll events for custom scrollbar

I have a test today at my uni. Will try to start that soon.

**Comment by sandy9808** [comment]
Can I try this ?

**Comment by sandy9808** [comment]
I don't know why but my custom scrollbar is not working in the mobile, but it works fine on desktop.

**Comment by imabp** [comment]
@nidhishs would you like to work on this issue ?
If no , I would definitely go with other person on  hold @sandy9808

**Comment by nidhishs** [comment]
I was going through the code base, and I believe you have used React. I was trying to learn React since a couple days, however I don't think I would be able to contribute meaningfully to the project. Sorry for the inconvenience.

**Comment by imabp** [comment]
That's fine @nidhishs . After you get clear with basics of React you can contribute to the other projects and issues too.
We love open source.

And our main aim is that only to help the contributors to learn and push themselves up.

**Comment by imabp** [comment]
Issue is assigned to @sandy9808 

Go ahead @sandy9808 , if you need any help reply in thread. itself

**Comment by sandy9808** [comment]
I am adding the css of custom scrollbar but i am not able to view the changes on mobile, it is visible only on desktop.

**Comment by imabp** [comment]
@sandy9808 Its fine, if not visible in mobile. Scrollbar in lesser screen size mobile, will break the aesthetic looks in mobile. 

We want for desktop only.

**Comment by imabp** [comment]
@sandy9808 when u send PR, make sure its sent to `development`

**Comment by sandy9808** [comment]
is this good ?
https://15a2681c-fb42-4e39-aa32-159886e2e269-5000.apps.codespaces.githubusercontent.com/

**Comment by imabp** [comment]
send PR, we will see on netlify deploy previews
