### ISSUE TITLE
Modify switch button for a pin switch

### ISSUE THREAD

**Issue by DaniAcu** [Ninja-Developers/Tech_Phantoms_website#77]
Hi, I would like to help to improve the switch button 

Now
![image](https://user-images.githubusercontent.com/26409015/94278935-cf96ed80-ff21-11ea-8a39-0aab67b08bc4.png)

Next
![sample](https://i.pinimg.com/originals/c6/5b/13/c65b13f534170fc05373b0bc907bd38a.gif)

**Comment by Souvikns** [comment]
wow, @DaniAcu the first one looks awesome.

> As hactoberfest starts from 1/oct, make a pr after that.

**Comment by DaniAcu** [comment]
Yeah, that it's the idea. If you could assign it to me, it will be awesome.
