### ISSUE TITLE
Decide Font and color 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#8]

**Comment by JoshuaPoddoku** [comment]
Few set of fonts I have selected

(Priority: Font Family)

Primary Font: Varela
Secondary Font: Josefin Slab
Other Font: Catamaran

![screely-1598895477949](https://user-images.githubusercontent.com/31725457/91749262-d65e6900-ebde-11ea-852b-2d15d323a7a9.png)

**Comment by Souvikns** [comment]
This looks good we can go with this.

**Comment by Souvikns** [comment]
@JoshuaPoddoku have a look in issue #15 if that is fine, we can use that color. 
> Then we would have finished choosing our color and typography, and could proceed in building the theme file.

**Comment by JoshuaPoddoku** [comment]
#15  Yes we can go for it!

**Comment by imabp** [comment]
As Joshua said, we will be using these fonts then.
@Souvikns  @JoshuaPoddoku 

Primary Font: Varela
Secondary Font: Josefin Slab
Other Font: Catamaran

And color scheme #15 issue we can refer.
