### ISSUE TITLE
Create chakra-ui theme file.

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Tech_Phantoms_website#91]
### use [this](https://chakra-ui.com/theme) for reference

**Comment by adithyaakrishna** [comment]
Hey, I would like to work on this @Souvikns

**Comment by Souvikns** [comment]
@adithyaakrishna go ahead, I am assigning you this issue.

**Comment by Souvikns** [comment]
@imabp can you brief all the theme constants, like color and typography that we are using.

**Comment by adithyaakrishna** [comment]
Thank you, Idk much about the Chakra UI but i would love to learn and do this if its okay :)

**Comment by Souvikns** [comment]
@adithyaakrishna We are migrating from chakra UI to material UI so I am closing this issue.

**Comment by adithyaakrishna** [comment]
Okay @Souvikns , I would contribute to that only :)
