### ISSUE TITLE
Remote link fix

### ISSUE THREAD

**Issue by RaisinTen** [Ninja-Developers/Tech_Phantoms_website#93]
In the [set it up section of the contributing documentation](https://github.com/Ninja-Developers/Tech_Phantoms_website/blob/master/CONTRIBUTING.md#3-set-it-up), it is mentioned that this is how we are supposed to add the `upstream`:
```sh
$ git remote add upstream https://github.com/Ninja-Developers/Tech_Phantoms_website
```
I think it would be more accurate if we append `.git` to the link or else it doesn't really work. May I change it to the following?
```
$ git remote add upstream https://github.com/Ninja-Developers/Tech_Phantoms_website.git
```
:slightly_smiling_face:

**Comment by imabp** [comment]
Thanks a lot for this issue. 
As it is documentation related issue, you can send PR directly to master.
