### ISSUE TITLE
Comment fix

### ISSUE THREAD

**Issue by RaisinTen** [Ninja-Developers/Tech_Phantoms_website#94]
In the [sync it section of the contributing documentation](https://github.com/Ninja-Developers/Tech_Phantoms_website/blob/master/CONTRIBUTING.md#4-sync-it), I think the comment associated with the code snippet can be fixed a bit with this:
```diff
- # Fetch all remote repositories and delete any deleted remote branches
+ # Fetch all remote branches and/or tags from the remote repository and delete any deleted remote branches
$ git fetch --all --prune
```
The change is based on a mix of [this](https://git-scm.com/docs/git-fetch#_description) and [this](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---all). May I fix it?
:slightly_smiling_face:

**Comment by imabp** [comment]
This is critical docs fault go ahead.
